### ISSUE TITLE
$src alias not found

### ISSUE THREAD

**Issue by michaelbromley** [pevey/sveltekit-vendure-starter-server-side#1]
On running `yarn vite dev` after a fresh clone & install, I ran into this error:

```
16:28:24 [vite] Error when evaluating SSR module /src/routes/+layout.svelte: failed to import "C:/src/app.postcss"
|- Error: Failed to load url C:/src/app.postcss (resolved id: C:/src/app.postcss) in C:/Development/temp/saluna/src/routes/+layout.svelte. Does the file exist?
```

I traced it to the generated `.sveklte-kit/tsconfig.json` file that contained this:

```json
{
	"compilerOptions": {
		"paths": {
			"$src/*": [
				"../../../../src/*"
			],
			"$lib": [
				"../src/lib"
			],
			"$lib/*": [
				"../src/lib/*"
			]
		},
```

I could fix this with the following change in `svelte.config.js`:

```diff
   kit: {
      adapter: adapter(),
      alias: {
-			'$src/*': '/src/*'
+			'$src/*': 'src/*'
		}
```

I'm on Windows by the way, in case that is relevant.

**Comment by pevey** [comment]
Hmm, this is interesting.  I'm on Linux.  This line is from the default Svelte starter project.  I made the change you made above, and it still seems to work on Linux.  I'm going to go ahead and push this change for now and also do some more research to see why the '/src/*' is the default in the skeleton project.
