### ISSUE TITLE
VENDURE_API_URL not defined in .env.example

### ISSUE THREAD

**Issue by michaelbromley** [pevey/sveltekit-vendure-starter-server-side#2]
Following the readme instructions I copied the example env file to `.env`, but in the [server/vendure/index.ts](https://github.com/pevey/saluna/blob/main/src/lib/server/vendure/index.ts#L3) file it is looking for `VENDURE_API_URL` which is not defined in the example env file.

So nothing loads and it took a little while to figure out why. Adding `VENDURE_API_URL=http://localhost:3000/shop-api` to my .env file fixed it.

**Comment by pevey** [comment]
Thanks, Michael.  I updated the config shape to use env vars that are pulled into saluna.config.ts.  When I did that, I didn't quite finished and left some essentials pieces referencing the old env vars directly.  This has been fixed now and will be in the next push.

**Comment by pevey** [comment]
Fixed in commit https://github.com/pevey/saluna/commit/b10e7e6f43d897386904e401df77ac907349015c.
